// <auto-generated />
using System;
using CollegeLMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CollegeLMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409220924_AddModuleGradeReleaseState")]
    partial class AddModuleGradeReleaseState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollegeLMS.API.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "ScheduledAt");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AssessmentGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("AssessmentId", "StudentId")
                        .IsUnique();

                    b.HasIndex("StudentId", "GradedAt");

                    b.ToTable("AssessmentGrades");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Deadline");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AssignmentGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("InstructorId", "GradedAt");

                    b.ToTable("AssignmentGrades");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceSessionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("AttendanceSessionId", "StudentId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AttendanceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByInstructorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByInstructorId");

                    b.HasIndex("ModuleId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseId", "Order");

                    b.ToTable("Modules", t =>
                        {
                            t.HasCheckConstraint("CK_Modules_Type", "\"Type\" IN ('Sequential', 'Compulsory', 'Optional')");
                        });
                });

            modelBuilder.Entity("CollegeLMS.API.Models.ModuleProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("FinalGrade")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsReleased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StudentId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ModuleProgresses", t =>
                        {
                            t.HasCheckConstraint("CK_ModuleProgress_Status", "\"Status\" IN ('InProgress', 'Passed', 'Failed')");
                        });
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimetableExceptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("TimetableExceptionId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.HasIndex("UserId", "Type", "CreatedAt");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Type", "\"Type\" IN ('General', 'ClassCancelled', 'ClassRescheduled', 'AssignmentDeadline', 'AssessmentDate', 'AssignmentGraded', 'FinalGradeReleased')");
                        });
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.TimetableException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RescheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("RescheduleEndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("RescheduleStartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("TimetableSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TimetableSlotId", "Date")
                        .IsUnique();

                    b.ToTable("TimetableExceptions", t =>
                        {
                            t.HasCheckConstraint("CK_TimetableExceptions_Status", "\"Status\" IN ('Cancelled', 'Rescheduled')");
                        });
                });

            modelBuilder.Entity("CollegeLMS.API.Models.TimetableSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int>("InstructorId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ModuleId", "DayOfWeek", "StartTime", "EndTime");

                    b.ToTable("TimetableSlots", t =>
                        {
                            t.HasCheckConstraint("CK_TimetableSlots_DayOfWeek", "\"DayOfWeek\" IN ('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')");
                        });
                });

            modelBuilder.Entity("CollegeLMS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Student', 'Instructor', 'Admin')");
                        });
                });

            modelBuilder.Entity("CourseEnrollment", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrollments", (string)null);
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Assessment", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Module", "Module")
                        .WithMany("Assessments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AssessmentGrade", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Assessment", "Assessment")
                        .WithMany("Grades")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.User", "Instructor")
                        .WithMany("AssessmentGradesGiven")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.User", "Student")
                        .WithMany("AssessmentGradesReceived")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Assignment", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Module", "Module")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AssignmentGrade", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.User", "Instructor")
                        .WithMany("AssignmentGradesGiven")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.Submission", "Submission")
                        .WithOne("AssignmentGrade")
                        .HasForeignKey("CollegeLMS.API.Models.AssignmentGrade", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AttendanceRecord", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.AttendanceSession", "AttendanceSession")
                        .WithMany("Records")
                        .HasForeignKey("AttendanceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.User", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AttendanceSession", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.User", "CreatedByInstructor")
                        .WithMany("AttendanceSessionsCreated")
                        .HasForeignKey("CreatedByInstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.Module", "Module")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByInstructor");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Course", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.User", "Instructor")
                        .WithMany("CoursesTeaching")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Module", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.ModuleProgress", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Module", "Module")
                        .WithMany("Progresses")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.User", "Student")
                        .WithMany("ModuleProgresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Notification", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Assessment", "Assessment")
                        .WithMany("Notifications")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CollegeLMS.API.Models.Assignment", "Assignment")
                        .WithMany("Notifications")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CollegeLMS.API.Models.Module", "Module")
                        .WithMany("Notifications")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CollegeLMS.API.Models.TimetableException", "TimetableException")
                        .WithMany("Notifications")
                        .HasForeignKey("TimetableExceptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CollegeLMS.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Assignment");

                    b.Navigation("Module");

                    b.Navigation("TimetableException");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Submission", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.TimetableException", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.TimetableSlot", "TimetableSlot")
                        .WithMany("Exceptions")
                        .HasForeignKey("TimetableSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimetableSlot");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.TimetableSlot", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.User", "Instructor")
                        .WithMany("TimetableSlotsTeaching")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.Module", "Module")
                        .WithMany("TimetableSlots")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CourseEnrollment", b =>
                {
                    b.HasOne("CollegeLMS.API.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeLMS.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Assessment", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Assignment", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.AttendanceSession", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Module", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Assignments");

                    b.Navigation("AttendanceSessions");

                    b.Navigation("Notifications");

                    b.Navigation("Progresses");

                    b.Navigation("TimetableSlots");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.Submission", b =>
                {
                    b.Navigation("AssignmentGrade");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.TimetableException", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.TimetableSlot", b =>
                {
                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("CollegeLMS.API.Models.User", b =>
                {
                    b.Navigation("AssessmentGradesGiven");

                    b.Navigation("AssessmentGradesReceived");

                    b.Navigation("AssignmentGradesGiven");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("AttendanceSessionsCreated");

                    b.Navigation("CoursesTeaching");

                    b.Navigation("ModuleProgresses");

                    b.Navigation("Notifications");

                    b.Navigation("Submissions");

                    b.Navigation("TimetableSlotsTeaching");
                });
#pragma warning restore 612, 618
        }
    }
}
